# Generated by Django 3.1.2 on 2020-10-27 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roulette',
            name='content_name',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=50, verbose_name='コンテンツ')),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destiny.roulette', verbose_name='ルーレット')),
            ],
            options={
                'verbose_name': 'コンテンツ',
                'verbose_name_plural': 'コンテンツ',
            },
        ),
    ]
