# Generated by Django 3.1.2 on 2020-10-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0002_auto_20201027_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='roulette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destiny.roulette', verbose_name='ルーレット'),
        ),
    ]
