# Generated by Django 3.1.2 on 2020-10-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0003_auto_20201028_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='roulette',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='destiny.roulette', verbose_name='ルーレット'),
            preserve_default=False,
        ),
    ]
