# Generated by Django 3.1.2 on 2020-10-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0004_auto_20201028_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='コンテンツ'),
        ),
        migrations.AlterField(
            model_name='content',
            name='roulette',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='destiny.roulette', verbose_name='ルーレット'),
        ),
    ]
