# Generated by Django 3.1.2 on 2020-10-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0005_auto_20201028_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='roulette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destiny.roulette', verbose_name='ルーレット'),
        ),
    ]
