# Generated by Django 3.1.2 on 2020-10-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0006_auto_20201028_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_name',
            field=models.CharField(default=1, max_length=50, verbose_name='コンテンツ'),
            preserve_default=False,
        ),
    ]
